# Generated by Django 3.0.8 on 2020-07-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('calculatedCredits', models.IntegerField()),
                ('registeredCredits', models.IntegerField()),
                ('creditsAchieved', models.IntegerField()),
                ('gradeAverage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredSubject',
            fields=[
                ('idSubject', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nameSubject', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=2)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_introduction.Profile')),
            ],
        ),
    ]
